git config --global alias.st 'status'
git config --global alias.aa 'add -A'
git config --global alias.ci 'commit -m'
git config --global alias.br 'branch'
git config --global alias.co 'checkout'
git config --global alias.cob 'checkout -b'
git config --global alias.dbl 'branch -d'
git config --global alias.dbr 'push origin --delete'